#!/usr/bin/python

import requests
import cherrypy
import json
import socket
import sys

squeeze_player = ""

def get_ip_address():
    s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
    s.connect(('192.168.0.101', 0))  # connecting to a UDP address doesn't send packets
    return s.getsockname()[0]

def squeeze_request(params):
    js = {"id":1,"method":"slim.request","params":[squeeze_player,params]}
    return requests.post('http://192.168.0.101:9001/jsonrpc.js', data=json.dumps(js)).json()['result']

class Root(object):
    exposed = True

class Api(object):
    exposed = True

    @cherrypy.tools.json_out()
    @cherrypy.tools.json_in()
    def POST(self):
        return squeeze_request(cherrypy.request.json)

if __name__ == '__main__':
    conf_api = {
        '/': {
            'request.dispatch': cherrypy.dispatch.MethodDispatcher(),
            'tools.response_headers.on': True,
            'tools.response_headers.headers': [('Content-Type', 'application/json')],
        }
    }

    conf_root = {
        '/': {
            'tools.staticdir.on': True,
            'tools.staticdir.dir': "/var/www",
            'tools.staticdir.index': "index.html"
        }
    }

    # Get our IP address as seen by the squeeze server
    ip = get_ip_address()

    # Establish our player id
    r = squeeze_request(["players"])
    player_count = r["count"]
    if player_count == 0:
        sys.exit(0)

    r = squeeze_request(["players",0,player_count])
    for p in r["players_loop"]:
        if p["ip"].startswith(ip):
          squeeze_player = p["playerid"]
    
    if squeeze_player == "":
        sys.exit(0)

    cherrypy.server.socket_host = "0.0.0.0"
    cherrypy.server.socket_port = 80

    cherrypy.tree.mount(Root(), '/', conf_root)
    cherrypy.tree.mount(Api(), '/api', conf_api)

    cherrypy.engine.start()
    cherrypy.engine.block()

